# Generated by Django 5.0.3 on 2026-06-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('is_guest', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tests.test')),
            ],
            options={
                'db_table': 'test_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('transferred', 'Transferred')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_events', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitations.testinvitation')),
            ],
            options={
                'db_table': 'invitation_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testinvitation',
            index=models.Index(fields=['token'], name='test_invita_token_aeca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='testinvitation',
            index=models.Index(fields=['test', 'is_used'], name='test_invita_test_id_69d67a_idx'),
        ),
        migrations.AddIndex(
            model_name='testinvitation',
            index=models.Index(fields=['invited_by', 'created_at'], name='test_invita_invited_ca22cc_idx'),
        ),
        migrations.AddIndex(
            model_name='testinvitation',
            index=models.Index(fields=['guest_user', 'is_used'], name='test_invita_guest_u_97df05_idx'),
        ),
        migrations.AddIndex(
            model_name='testinvitation',
            index=models.Index(fields=['expires_at'], name='test_invita_expires_e6d21e_idx'),
        ),
    ]
