# Generated by Django 5.0.3 on 2026-07-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitationEvent',
        ),
    ]
