# Generated by Django 5.0.3 on 2026-06-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test', '0002_alter_test_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.CharField(blank=True, max_length=255)),
                ('sub_topic', models.CharField(blank=True, max_length=255)),
                ('specific_topic', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(max_length=20)),
                ('num_questions', models.IntegerField()),
                ('num_answers', models.IntegerField()),
                ('language', models.CharField(default='es', max_length=2)),
                ('generation_mode', models.CharField(default='guided', max_length=20)),
                ('ai_prompt', models.TextField(blank=True)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('response_time', models.FloatField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_request__user_id_290115_idx'), models.Index(fields=['status'], name='ai_request__status_1b31a9_idx'), models.Index(fields=['generation_mode'], name='ai_request__generat_17d3bd_idx')],
            },
        ),
    ]
