# Generated by Django 5.0.3 on 2026-06-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_configs',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='system_conf_key_4990ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=7)),
                ('max_requests', models.IntegerField(default=5)),
                ('used_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quotas',
                'ordering': ['-month_year'],
                'indexes': [models.Index(fields=['user_id', 'month_year'], name='user_quotas_user_id_435993_idx'), models.Index(fields=['month_year'], name='user_quotas_month_y_f82032_idx'), models.Index(fields=['max_requests'], name='user_quotas_max_req_98d6e0_idx'), models.Index(fields=['used_requests'], name='user_quotas_used_re_d67581_idx')],
                'unique_together': {('user', 'month_year')},
            },
        ),
    ]
