# Generated by Django 5.0.3 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.CharField(db_index=True, max_length=200)),
                ('sub_topic', models.CharField(db_index=True, max_length=200)),
                ('specific_topic', models.CharField(db_index=True, max_length=200)),
                ('is_predefined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topics',
                'indexes': [models.Index(fields=['main_topic'], name='topics_main_to_7b95fc_idx'), models.Index(fields=['main_topic', 'sub_topic'], name='topics_main_to_44c819_idx'), models.Index(fields=['main_topic', 'sub_topic', 'specific_topic'], name='topics_main_to_a49daa_idx')],
                'unique_together': {('main_topic', 'sub_topic', 'specific_topic')},
            },
        ),
    ]
